export const screenMeta = {
  home: {
    title: "StockLedger",
    kicker: "Home",
    label: "Home",
    guide: "Start here when you want the shortest path into the local prototype.",
  },
  dashboard: {
    title: "Stock Overview",
    kicker: "Inventory",
    label: "Stock Overview",
    guide: "Start here. Check total stock first, then look at one location when you need detail.",
  },
  sales: {
    title: "Sales",
    kicker: "Daily Work",
    label: "Sales",
    guide: "Create sales, track one-time and recurring orders, and post stock deductions only when work is fulfilled.",
  },
  purchases: {
    title: "Purchases",
    kicker: "Daily Work",
    label: "Purchases",
    guide: "Plan supplier orders, receive deliveries, and post stock-in events from confirmed receiving work.",
  },
  compose: {
    title: "Stock Actions",
    kicker: "Actions",
    label: "Stock Actions",
    guide: "Record stock work, product lifecycle work, and send the pending batch from one place.",
  },
  clients: {
    title: "Clients",
    kicker: "Relationships",
    label: "Clients",
    guide: "Manage customer profiles, order patterns, client menus, and activity without exposing private contact details unnecessarily.",
  },
  suppliers: {
    title: "Suppliers",
    kicker: "Relationships",
    label: "Suppliers",
    guide: "Track suppliers, purchase history, delivery expectations, and receiving variance.",
  },
  menus: {
    title: "Menus",
    kicker: "Relationships",
    label: "Menus",
    guide: "Map sellable client menu items to stock products so sales deduct inventory deterministically.",
  },
  products: {
    title: "Products",
    kicker: "Catalog",
    label: "Products",
    guide: "Use this as a catalog view. Product changes are prepared in Stock Actions so they enter the same work queue.",
  },
  locations: {
    title: "Locations",
    kicker: "Relationships",
    label: "Locations",
    guide: "Maintain stock places such as storage, bar, kitchen, cellar, and future delivery zones.",
  },
  reports: {
    title: "Reports",
    kicker: "Control",
    label: "Reports",
    guide: "Review stock, sales, purchases, clients, variance, and audit activity by decision group.",
  },
  audit: {
    title: "Audit Trail",
    kicker: "History",
    label: "Audit Trail",
    guide: "Use this when a number looks wrong. It shows who recorded each change and how stock was affected.",
  },
  users: {
    title: "Users & Roles",
    kicker: "Control",
    label: "Users & Roles",
    guide: "Plan staff access, role assignment, device trust, and privacy-safe user administration.",
  },
  settings: {
    title: "Settings",
    kicker: "Control",
    label: "Settings",
    guide: "Configure site defaults, sync behavior, numbering, offline retention, and tenant-safe data handling.",
  },
};

export const navigationGroups = [
  {
    label: "Daily Work",
    items: ["home", "dashboard", "sales", "purchases", "compose"],
  },
  {
    label: "Relationships",
    items: ["clients", "suppliers", "menus", "products", "locations"],
  },
  {
    label: "Control",
    items: ["reports", "audit", "users", "settings"],
  },
];

export const eventLabels = {
  STOCK_IN: "Stock In",
  STOCK_OUT: "Use Stock",
  STOCK_TRANSFER: "Move Stock",
  STOCK_ADJUSTMENT: "Correct Stock Count",
  STOCK_REVERT: "Undo Record",
  PRODUCT_CREATED: "Enroll New Product",
  PRODUCT_DEACTIVATED: "Suspend Product",
  PRODUCT_REACTIVATED: "Reactivate Product",
};

export const actionTabLabels = {
  STOCK_IN: "Stock In",
  STOCK_OUT: "Use Stock",
  STOCK_TRANSFER: "Move Stock",
  STOCK_ADJUSTMENT: "Correct Count",
  STOCK_REVERT: "Undo Record",
  PRODUCT_CREATED: "Enroll New Product",
  PRODUCT_DEACTIVATED: "Suspend Product",
  PRODUCT_REACTIVATED: "Reactivate Product",
};

export const REVERTIBLE_EVENT_TYPES = new Set(["STOCK_IN", "STOCK_OUT", "STOCK_TRANSFER", "STOCK_ADJUSTMENT"]);

export const ACTION_TEMPLATES = {
  STOCK_IN: {
    template: "Stock In Template",
    summary: "Product arrived into one location.",
    help: "Use this for supplier delivery, restock, or opening stock. Choose where the stock arrived.",
    requiredFields: ["product_id", "to_location", "quantity"],
    sourceLabel: "Not Used",
    destinationLabel: "Arrived At",
    quantityLabel: "Amount Received",
    reasonPlaceholder: "Example: supplier delivery accepted",
    showFromLocation: false,
    showToLocation: true,
    showOriginalEvent: false,
    quantityEditable: true,
    requiresPositiveQuantity: true,
    defaults: {
      from_location: "",
      to_location: "Dry Store",
      quantity: 1,
      original_event_id: "",
    },
  },
  STOCK_OUT: {
    template: "Use Stock Template",
    summary: "Product left one location.",
    help: "Use this when stock was sold, used, wasted, or broken. Choose where it left from.",
    requiredFields: ["product_id", "from_location", "quantity"],
    sourceLabel: "Left From",
    destinationLabel: "Not Used",
    quantityLabel: "Amount Used",
    reasonPlaceholder: "Example: evening service use",
    showFromLocation: true,
    showToLocation: false,
    showOriginalEvent: false,
    quantityEditable: true,
    requiresPositiveQuantity: true,
    defaults: {
      from_location: "Main Bar",
      to_location: "",
      quantity: 1,
      original_event_id: "",
    },
  },
  STOCK_TRANSFER: {
    template: "Transfer Template",
    summary: "Product moved between two locations.",
    help: "Use this when stock moved from one place to another. Choose both the starting place and ending place.",
    requiredFields: ["product_id", "from_location", "to_location", "quantity"],
    sourceLabel: "Move From",
    destinationLabel: "Move To",
    quantityLabel: "Amount Moved",
    reasonPlaceholder: "Example: moved to Main Bar for opening",
    showFromLocation: true,
    showToLocation: true,
    showOriginalEvent: false,
    quantityEditable: true,
    requiresPositiveQuantity: true,
    defaults: {
      from_location: "Dry Store",
      to_location: "Main Bar",
      quantity: 1,
      original_event_id: "",
    },
  },
  STOCK_ADJUSTMENT: {
    template: "Correct Stock Count Template",
    summary: "A hand count found a difference.",
    help: "Choose the product and location you counted. Enter what you physically counted - the system shows the current count and calculates the difference for you.",
    requiredFields: ["product_id", "to_location", "quantity"],
    sourceLabel: "Count Location",
    destinationLabel: "Not Used",
    quantityLabel: "Correction Amount",
    reasonPlaceholder: "Example: physical count difference",
    showFromLocation: false,
    showToLocation: true,
    showOriginalEvent: false,
    quantityEditable: true,
    isPhysicalCount: true,
    requiresPositiveQuantity: false,
    defaults: {
      from_location: "",
      to_location: "Main Bar",
      quantity: 1,
      physical_count: "",
      original_event_id: "",
    },
  },
  STOCK_REVERT: {
    template: "Undo Record Template",
    summary: "Cancel one earlier movement without deleting it.",
    help: "Use this to undo a mistake. Choose the original reversible movement; the product and location are inherited from that record.",
    requiredFields: ["original_event_id"],
    sourceLabel: "Original Location",
    destinationLabel: "Not Used",
    quantityLabel: "Reversal Amount",
    reasonPlaceholder: "Example: wrong product was selected",
    showFromLocation: false,
    showToLocation: false,
    showOriginalEvent: true,
    quantityEditable: false,
    requiresPositiveQuantity: true,
    defaults: {
      from_location: "",
      to_location: "",
      quantity: 1,
      original_event_id: "",
    },
  },
  PRODUCT_CREATED: {
    template: "Product Enrollment Template",
    summary: "Add a product to the catalog before stock work references it.",
    help: "Use this for a new product. Enrollment is saved to the same work queue as inventory records.",
    kind: "product-create",
    reasonPlaceholder: "Example: new seasonal item",
    defaults: {
      from_location: "",
      to_location: "",
      quantity: 0,
      original_event_id: "",
    },
  },
  PRODUCT_DEACTIVATED: {
    template: "Product Suspension Template",
    summary: "Suspend a product and close any replayed stock balance.",
    help: "Use this when a product should stop appearing in stock work. Any non-zero balance is queued as grouped closure work.",
    kind: "product-suspend",
    reasonPlaceholder: "Example: seasonal item removed from menu",
    defaults: {
      from_location: "",
      to_location: "",
      quantity: 0,
      original_event_id: "",
    },
  },
  PRODUCT_REACTIVATED: {
    template: "Product Reactivation Template",
    summary: "Return a suspended product to active use.",
    help: "Use this when a suspended product should be selectable again. Reactivation does not create stock movement.",
    kind: "product-reactivate",
    reasonPlaceholder: "Example: seasonal item returned",
    defaults: {
      from_location: "",
      to_location: "",
      quantity: 0,
      original_event_id: "",
    },
  },
};

export function actionTemplate(type) {
  return ACTION_TEMPLATES[type] ?? ACTION_TEMPLATES.STOCK_OUT;
}
